Finished events list component
k1k8r/it-house pull request #1
Opened 2021-06-09 09:45 UTC by k1k8r

2021-06-09 09:56 UTC, basters requested changes

2021-06-09 09:56 UTC, basters commented on src/app/auth/services/auth.service.ts
> +  public get isLogged(): boolean {
Pretty strange that you have used getter and instance method together.

If you want to have getter isLogged than you have to remove isLogged() instance method. You don't need to have them both

2021-06-09 16:25 UTC, AntonGorelov requested changes

2021-06-09 16:25 UTC, AntonGorelov commented on src/app/auth/guards/is-logged-in.guard.ts
>      Observable<boolean | UrlTree> | Promise<boolean | UrlTree> | boolean | UrlTree {
@k1k8r you don't need to specify union of types since your guard returns just boolean type. Will be better to keep just one type.

2021-06-10 08:22 UTC, AntonGorelov approved these changes

2021-06-10 08:25 UTC, merged